export const metadata = {
  metadataBase: new URL("https://genforgestudio.com"),
  title: "Irvine Hospitality – FF&E E-commerce & Admin Case Study | GenForge",
  description:
    "Hospitality-grade FF&E/OS&E storefront and admin: −80% manual catalog edits, higher engagement, and SEO gains with industry taxonomy and SSR deployment.",
  keywords: [
    "FF&E e-commerce",
    "OS&E procurement",
    "catalog management",
    "Next.js case study",
    "admin panel",
    "role-based workflows",
    "GenForge Studio projects",
    "best website development company",
"top website development agency",
"affordable website design company",
"custom web application development",
"full-stack development services",
"e-commerce website design and development",
"best app development company",
"mobile app development agency",
"affordable app developers",
"hire web developers",
"hire app developers",
"small business website design",
"website design for startups",
"app development for small business",
"custom software solutions for small business",
"best website development company in India",
"top web development agency in India",
"best app development company in India",
"website development company in Ahmedabad",
"web development company in Surat",
"app development company in Ahmedabad",
"app development company in Surat",
"website development company in Lucknow",
"app development company in Lucknow",
"website development company in Gurugram",
"app development company in Gurugram",
"website development company in Noida",
"app development company in Noida",
"website development company in Delhi",
"app development company in Delhi",
"website development company in Haryana",
"app development company in Haryana",
"website development company in Mumbai",
"app development company in Mumbai",
"website development company in Bangalore",
"app development company in Bangalore",
"website development company in Pune",
"app development company in Pune",
"best website development company in USA",
"app development company in USA",
"web development agency in UK",
"app development agency in UK",
"website development company in Australia",
"app development company in Australia",
"website development company in Canada",
"app development company in Canada",
"website development company in Dubai",
"app development company in Dubai",
"website development company in Singapore",
"app development company in Singapore",
"website development company in Germany",
"app development company in Germany",
"website development company in France",
"app development company in France",
"global website development agency",
"international app development company",
"best SaaS development company",
"custom SaaS product development",
"e-commerce app development company",
"e-commerce website design agency",
"hire Next.js developers",
"hire React developers",
"hire Node.js developers",
"website design for local businesses",
"website design for restaurants",
"website design for retail stores",
"website design for service providers",
"website redesign services",
"website performance optimization",
"SEO-friendly website design",
"multi-language website development",
"secure web hosting services",
"web application maintenance",
"cross-platform mobile app development",
"progressive web apps development",
"business automation solutions",
"real-time web applications",
"conversion rate optimization services"
  ],
  alternates: { canonical: "/projects/irvine-hospitality" },
  openGraph: {
    title: "Irvine Hospitality — FF&E E-commerce & Admin (Case Study)",
    description:
      "Modern hospitality storefront with SSR, role-based admin, and SEO-optimized FF&E taxonomy. −80% catalog edits, higher engagement.",
    url: "https://genforgestudio.com/projects/irvine-hospitality",
    siteName: "GenForge Studio",
    type: "article",
    locale: "en_US",
    images: [
      {
        url: "/og/projects/irvine-hospitality.jpg",
        width: 1200,
        height: 630,
        alt: "Irvine Hospitality – FF&E E-commerce & Admin case study preview",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Irvine Hospitality — FF&E E-commerce & Admin",
    description:
      "FF&E storefront with SSR & role-based admin: −80% manual catalog edits, better engagement, SEO optimized.",
    images: ["/og/projects/irvine-hospitality.jpg"],
  },
  robots: {
    index: true,
    follow: true,
    maxSnippet: -1,
    maxImagePreview: "large",
  },
};

export default function IrvineHospitalityLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}