export const metadata = {
  metadataBase: new URL("https://genforgestudio.com"),
  title: "Spark & Stitch – UPI-first E-commerce Case Study | GenForge",
  description:
    "How GenForge built a fast, UPI-first e-commerce stack with Cashfree and Cloudinary—≤2.0s LCP, +7–12% checkout success, and −45–60% image weight.",
  keywords: [
    "UPI ecommerce case study",
    "Cashfree integration",
    "Cloudinary optimization",
    "Next.js performance",
    "ecommerce checkout success",
    "LCP improvement",
    "GenForge Studio projects",
    "Ahmedabad India",
    "best website development company",
"top website development agency",
"affordable website design company",
"custom web application development",
"full-stack development services",
"e-commerce website design and development",
"best app development company",
"mobile app development agency",
"affordable app developers",
"hire web developers",
"hire app developers",
"small business website design",
"website design for startups",
"app development for small business",
"custom software solutions for small business",
"best website development company in India",
"top web development agency in India",
"best app development company in India",
"website development company in Ahmedabad",
"web development company in Surat",
"app development company in Ahmedabad",
"app development company in Surat",
"website development company in Lucknow",
"app development company in Lucknow",
"website development company in Gurugram",
"app development company in Gurugram",
"website development company in Noida",
"app development company in Noida",
"website development company in Delhi",
"app development company in Delhi",
"website development company in Haryana",
"app development company in Haryana",
"website development company in Mumbai",
"app development company in Mumbai",
"website development company in Bangalore",
"app development company in Bangalore",
"website development company in Pune",
"app development company in Pune",
"best website development company in USA",
"app development company in USA",
"web development agency in UK",
"app development agency in UK",
"website development company in Australia",
"app development company in Australia",
"website development company in Canada",
"app development company in Canada",
"website development company in Dubai",
"app development company in Dubai",
"website development company in Singapore",
"app development company in Singapore",
"website development company in Germany",
"app development company in Germany",
"website development company in France",
"app development company in France",
"global website development agency",
"international app development company",
"best SaaS development company",
"custom SaaS product development",
"e-commerce app development company",
"e-commerce website design agency",
"hire Next.js developers",
"hire React developers",
"hire Node.js developers",
"website design for local businesses",
"website design for restaurants",
"website design for retail stores",
"website design for service providers",
"website redesign services",
"website performance optimization",
"SEO-friendly website design",
"multi-language website development",
"secure web hosting services",
"web application maintenance",
"cross-platform mobile app development",
"progressive web apps development",
"business automation solutions",
"real-time web applications",
"conversion rate optimization services"
  ],
  alternates: {
    canonical: "/projects/spark-and-stitch",
  },
  openGraph: {
    title: "Spark & Stitch — UPI-first E-commerce Case Study",
    description:
      "Fast storefront, UPI-first checkout via Cashfree, Cloudinary media pipeline, realtime admin. ≤2.0s LCP, +7–12% checkout success.",
    url: "https://genforgestudio.com/projects/spark-and-stitch",
    siteName: "GenForge Studio",
    type: "article",
    locale: "en_IN",
    images: [
      {
        url: "/og/projects/spark-and-stitch.jpg", // ← replace with your actual OG image
        width: 1200,
        height: 630,
        alt: "Spark & Stitch — GenForge e-commerce case study preview",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Spark & Stitch — UPI-first E-commerce Case Study",
    description:
      "Cashfree UPI, Cloudinary media, realtime admin. ≤2.0s LCP, +7–12% checkout success, −45–60% image weight.",
    images: ["/og/projects/spark-and-stitch.jpg"], // same image as OG
  },
  robots: { index: true, follow: true, maxSnippet: -1, maxImagePreview: "large" },
};

export default function SparkAndStitchLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}